### ISSUE TITLE
"React app" in title of demo site 

### ISSUE THREAD

**Issue by arthurzenika** [zenika-open-source/react-portraits#3]
https://zenika-open-source.github.io/react-portraits/ has "React app" title.

**Comment by arthurzenika** [comment]
description "Web site created using create-react-app" can probably be changed too. 

One can test with https://embed.ly/docs/explore/oembed?url=https%3A%2F%2Fzenika-open-source.github.io%2Freact-portraits%2F

**Comment by FourmiPanda** [comment]
Fixed
